### ISSUE TITLE
Can we give own specified wallpapers ?

### ISSUE THREAD

**Issue by shivdhwaj** [bharadwaj-raju/WeatherDesk#1]
We can give own specified wallpapers or we can make the arrangements to have some cool urls to have them once connected to internet to download on the local storage and use it.

**Comment by bharadwaj-raju** [comment]
It's a bit unclear what you're asking, but it works on any set of local files. All you have to do is put all the files in a folder and name them according to the [rules](https://github.com/bharadwaj-raju/WeatherDesk#naming-of-pictures). Then tell it to use that directory by using `--dir /path/to/directory`
