### ISSUE TITLE
Use /dev/shm/somedir or /tmp/somefile for KDE >4

### ISSUE THREAD

**Issue by cmdrkotori** [bharadwaj-raju/WeatherDesk#10]
As you may be aware, directly setting a custom wallpaper for KDE isn't really possible at the moment because the api is not exposed for security reasons.

However this can mitigated by asking the user to point kde's desktop slideshow at a designated folder with a smallish timeout (say, 4 seconds).  The trick I have found is to have exactly one file with a randomized filename in a folder. On each wallpaper change, generate a new random name and move the new file in with it, and then delete the old file. It will work most of the time because collisions are very rare.

Example here, line 164-173 at https://github.com/cmdrkotori/qt314wall/blob/master/main.cpp#L164

**Comment by bharadwaj-raju** [comment]
I've committed an experimental implementation of what you say. Please test if it works.

Also, is there a way to set the wallpaper plugin to slideshow from the command line?

**Comment by bharadwaj-raju** [comment]
Also, is `/dev/shm` normal user-writable?
