### ISSUE TITLE
Applescript doesn't like single quotes

### ISSUE THREAD

**Issue by baztastic** [bharadwaj-raju/WeatherDesk#2]
Minor fix for OS X errors, replacing single quotes with double quotes, and removing "to":

Desktop.py, lines 270-274:
```python
                OSX_SCRIPT = '''tell application "Finder"
set desktop picture to POSIX file "%s"
end tell
                ''' % image
```

**Comment by bharadwaj-raju** [comment]
You're right about the single quotes, but the `to` is required. Fixing.

**Comment by baztastic** [comment]
The `to` throws an error for me:
`.weatherdesk_script.sh:26:29: script error: A end of line can’t go after this “to”. (-2740)`
For multiline `tell`s you don't need the `to`.

**Comment by bharadwaj-raju** [comment]
Oh, I see. You mean the `to` after `"Finder"` - I thought you meant the `to` after `picture`. Fixing.

**Comment by bharadwaj-raju** [comment]
Fix committed. Please test.

**Comment by bharadwaj-raju** [comment]
Also, does the AppleScript Python API (`appscript`) not work? Because the script file is meant to be called only when that doesn't work.

**Comment by baztastic** [comment]
Yep works for me, thanks!

Also just so you know, on OS X, if the "Desktop & Screen Saver" preference is set to automatically change every X minutes, it resets the background immediately after your script changes it, so the auto change setting should be changed in preferences before using your app. Maybe that could be put in the Readme.

Thanks for a cool little app!

**Comment by baztastic** [comment]
Well `appscript` is not installed by default on my system - it's a fresh install of python3 via homebrew...

**Comment by bharadwaj-raju** [comment]
`README` updated.

**Comment by bharadwaj-raju** [comment]
@baztastic I've included a note in the `README`, but can you please provide a screenshot of the option to be disabled, in order to supplement the note?

**Comment by baztastic** [comment]
Yep, here's the screenshot: [imgur](http://imgur.com/BFi1GHG)
