### ISSUE TITLE
Avoid naked exceptions

### ISSUE THREAD

**Issue by cclauss** [bharadwaj-raju/WeatherDesk#21]
See: https://realpython.com/blog/python/the-most-diabolical-python-antipattern/

Also, the code fails numerous PEP-8 tests.

**Comment by bharadwaj-raju** [comment]
I've added logging and now we are only catching specific exceptions, whose stack traces will be printed.

Now, if you would please list all PEP-8 fails, I'll fix them.

**Comment by bharadwaj-raju** [comment]
Using `pep8`, I fixed most of the fails, although some are unfixable without breaking our program.
