### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by tankerkiller125** [bharadwaj-raju/WeatherDesk#37]
The readme says that it supports windows, but it seems that it is not updating the wall paper, (windows 10) looking at the Desktop.py it seems as if its looking for some .bat file after it runs the rundll3d.exe line but that .bat file doesn't exist.

**Comment by bharadwaj-raju** [comment]
The program should be making the bat file itself before running it.

What does the following in a Python shell output on your system?

```python
>>> import os
>>> os.abspath(os.path.expanduser('~/'))
```

I only tested the script on Windows 7.

**Comment by tankerkiller125** [comment]
I ended up fixing the Desktop.py script I'll make a pull request for it 😄

**Comment by bharadwaj-raju** [comment]
Thanks! Merged.
