### ISSUE TITLE
Default wallpapers library

### ISSUE THREAD

**Issue by ivandokov** [bharadwaj-raju/WeatherDesk#4]
I think you should add default wallpapers library so it is easier to try the software - run it and it works.
Now I see that I have to find wallpapers, rename them and then try it.

**Comment by bharadwaj-raju** [comment]
1. It would be hard to find freely-licensed, good wallpapers

2. The goal is to _keep it simple_ -- no bloat.

Even if I would agree to have a default library, I'll maintain it in a separate repository -- possibly making install even more complicated.

Now, if we were to provide images for all options (simple weather-only, to the most detailed `--time 4`), it would add a few 10s of megabytes to the download. Then we have to provide for all resolutions...

We already have a ready-to-go, named wallpaper set ([this](http://imgur.com/a/snB5O)). I suppose if we mention it as a recommended set in the `README`, that'd solve the problems you said. All they have to do is extract it into a folder.

**Comment by ivandokov** [comment]
I think you can use this website to find wallpapers http://www.uhdwallpapers.org/p/creative-commons-images.html and add the license to the download archive.
Of course you can link the wallpapers set in the README. I don't think it's required to be in the install process, but additional install step will be cool.

**Comment by bharadwaj-raju** [comment]
The wallpaper set is now prominently featured in the `README`.
