### ISSUE TITLE
Trying to set city - Command not found

### ISSUE THREAD

**Issue by claudemontreal** [bharadwaj-raju/WeatherDesk#43]
I tried:
weatherdesk.py [-c name [Montreal]]
weatherdesk.py : command not found

python3 WeatherDesk.py [-c name [Montreal]]
python3: can't open file 'WeatherDesk.py': [Errno 2] No such file or directory

**Comment by bharadwaj-raju** [comment]
well, where did you download WeatherDesk.py to? give python3 that path.

also, this repo is old and doesn't work anymore. use https://gitlab.com/bharadwaj-raju/WeatherDesk.
